title: "My Wazuh Ambassador Blog"
description: "Tutorials about Wazuh"
theme: minima        # built-in Pages theme
plugins:
  - jekyll-feed
author:
  name: Jos√© Raeiro
  url: https://wazuh.com/ambassadors/jose-raeiro/
